Blog_Project/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('detaile/<int:post_id>/', views.post_details, name='detaile'),
    path('programming', views.dev, name='programming'),
    path('Ethical_Hacking', views.EH, name='EH'),
    path('Markrting', views.Mark, name='Marketing'),
    path('Another', views.Another, name='Another'),
    path('new_post', views.PostCreatView.as_view(), name='new_post'),
    path('detaile/<slug:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('detaile/<slug:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),    
]

Blog_Project/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('blog.urls')),
    path('' , include('user.urls')),
]

Blog_Project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

STATUS_CHOICES = (
    (("programming"), ("programming")),
    (("Ethical Hacking"), ("Ethical Hacking")),
    (("Marketing"), ("Marketing")),
    (("Another"), ("Another")),
)
class Post(models.Model):
    title = models.CharField(max_length=100)
    title1 = models.CharField(max_length=100, null=True)
    title2 = models.CharField(max_length=100, null=True)
    content = models.TextField()
    content2 = models.TextField(null=True)
    post_date = models.DateTimeField(default=timezone.now)
    post_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categry = models.CharField(max_length=50 ,null=True, choices=STATUS_CHOICES, default='Another')
    image = models.ImageField(default='default_post.png', upload_to='post_pics')
    image2 = models.ImageField(default='', null=True, upload_to='post_pics2')
    
    def __str__(self):
        return f'{self.title} in {self.categry}'
    
    def  get_absolute_url(self):
        # return f'/detail/{self.pk}'
        return reverse('detaile', args=[self.pk])
    
    class Meta:
        ordering = ('-post_date', )
        
        
        
class CommentSysteme(models.Model):
    body = models.TextField(null=True)
    coment_date = models.DateTimeField(default = timezone.now)
    name = models.ForeignKey(User,null=True, on_delete=models.CASCADE)
    post = models.ForeignKey(Post,null=True, on_delete=models.CASCADE, related_name='comment')
    
    
    def __str__(self):
        return f'{self.name} commented on {self.post}'
    
    class Meta:
        ordering = ('-coment_date', )
        
        
        
        
        
        

    

Blog_Project/blog/forms.py
from django import forms
from .models import Post


# from for comments
        
        
        
        
class PostCreatForm(forms.ModelForm):
    title = forms.CharField(label='Title of Post')
    title1 = forms.CharField(label='Title of the first paragraph', help_text='Title of first paragraph', required=False)
    title2 = forms.CharField(label='Title of the second paragraph', help_text='If you have a second paragraph, enter its title here', required=False)
    content = forms.CharField(label='Content of first paragraph', widget = forms.Textarea)
    content2 = forms.CharField(label='if you have a seconde paragraph', widget = forms.Textarea, help_text='If you have a second paragraph, enter it here', required=False)
    image2 = forms.ImageField(label='if you have second image', required=False)
    class Meta:
        model = Post
        fields = ['title','title1', 'content','title2','content2', 'image', 'image2','categry']
        
        

        
        
        

Blog_Project/blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Post,CommentSysteme
from .forms import PostCreatForm
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages



def home(request):
    l_post = Post.objects.all()
    paginator = Paginator(l_post, 5)
    page = request.GET.get('page')
    try:
        l_post = paginator.page(page)
    except PageNotAnInteger:
        l_post = paginator.page(1)
    except EmptyPage:
        l_post = paginator.page(paginator.num_pages)
        
    context = {
        'title' : 'home',
        'l_post': l_post,
        'page' : page,
        
    }
    return render(request , 'blog/index.html', context)


def post_details(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comment.all()
    if request.method == 'POST':
        user = request.user

        body = request.POST.get('body')

        comment = CommentSysteme(name=user, post=post, body=body)

        comment.save()

        return redirect('detaile',post_id)
    
    else: 
        return render(request, 'blog/detail.html',context = {
            'title' : post.title,
            'post' : post,
            'comments':comments,
        })






# Category
def dev(request):
    l_post = Post.objects.all()
    paginator = Paginator(l_post, 5)
    page = request.GET.get('page')
    try:
        l_post = paginator.page(page)
    except PageNotAnInteger:
        l_post = paginator.page(1)
    except EmptyPage:
        l_post = paginator.page(paginator.num_pages)
    context = {
        'title' : 'Developpment',
        'l_post' : Post.objects.filter(categry='programming'),
        'page' : page,
    }
    return render(request , 'Category/Dev.html', context)

def EH(request):
    l_post = Post.objects.all()
    paginator = Paginator(l_post, 5)
    page = request.GET.get('page')
    try:
        l_post = paginator.page(page)
    except PageNotAnInteger:
        l_post = paginator.page(1)
    except EmptyPage:
        l_post = paginator.page(paginator.num_pages)
    context = {
        'title' : 'Ethical Hacking',
        'l_post' : Post.objects.filter(categry='Ethical Hacking'),
        'page' : page,
    }
    return render(request , 'Category/Eh.html', context)

def Mark(request):
    l_post = Post.objects.all()
    paginator = Paginator(l_post, 5)
    page = request.GET.get('page')
    try:
        l_post = paginator.page(page)
    except PageNotAnInteger:
        l_post = paginator.page(1)
    except EmptyPage:
        l_post = paginator.page(paginator.num_pages)
    context = {
        'title' : 'Marketing',
        'l_post' : Post.objects.filter(categry='Marketing'),
        'page' : page,
    }
    return render(request , 'Category/Mark.html', context)

def Another(request):
    l_post = Post.objects.all()
    paginator = Paginator(l_post, 5)
    page = request.GET.get('page')
    try:
        l_post = paginator.page(page)
    except PageNotAnInteger:
        l_post = paginator.page(1)
    except EmptyPage:
        l_post = paginator.page(paginator.num_pages)
    context = {
        'title' : 'Another',
        'l_post' : Post.objects.filter(categry='Another'),
        'page' : page,
    }
    return render(request , 'Category/Another.html', context)




class PostCreatView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['title', 'content', 'image','categry']
    template_name = 'blog/new_post.html'
    form_class = PostCreatForm
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # to add context to class
    # def get_context_data(self, **kwargs):
    #     contact = ContactUs.objects.all()
    #     context = super().get_context_data(**kwargs)
    #     context['message'] = contact
    #     return context



class PostUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    form_class = PostCreatForm
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # Check if the user is the owner of the post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False
        
    # to add context to class
    # def get_context_data(self, **kwargs):
    #     contact = ContactUs.objects.all()
    #     context = super().get_context_data(**kwargs)
    #     context['message'] = contact
    #     return context
    



class PostDeleteView(DeleteView, LoginRequiredMixin, UserPassesTestMixin):
    model = Post
    success_url = '/'
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
    # to add context to class
    # def get_context_data(self, **kwargs):
    #     contact = ContactUs.objects.all()
    #     context = super().get_context_data(**kwargs)
    #     context['message'] = contact
    #     return context
    
    
    

def contact(request):
        
    context = {
        'title' : 'contact',
    }
    return render(request , 'blog/contact.html', context)






Blog_Project/blog/templates/blog/add_comment.html
                        {% if user.is_authenticated %}
                        <div class="blog-card3">
                            <h2 class="h2">Add Comment</h2>

                            <div class="blog-content-wrapper">

                                <form method="post" style="height:270px;">
                                    {% csrf_token %}
                                    {% comment %} {{comment_form}} {% endcomment %}
                                    <label for="id_body" class="h4">Comment:</label>
                                    <textarea name="body" cols="40" rows="10" required id="body"></textarea>
                                    <input type="submit" value="Submit">
                                </form>

                            </div>

                        </div>
                        {% endif %}

Blog_Project/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--
    - favicon
  -->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}" type="image/x-icon">

  <!--
    - custom css link
  -->
  <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/mainblog002.css'%}">

  <!--
    - google font link
  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">
  {% if title %}
  <title>Blogger | {{title}}</title>
  {% else %}
  <title>Blogger</title>
  {% endif %}

</head>
{% block content %}
{% endblock content %}

Blog_Project/blog/templates/blog/component.html
{% load static %}
<div class="aside">

    <div class="topics">

        <h2 class="h2">Topics</h2>

        <a href="{% url 'programming' %}" class="topic-btn">
            <div class="icon-box">
                <i class="fa-solid fa-code"></i>
            </div>

            <p>programming</p>
        </a>

        <a href="{% url 'EH' %}" class="topic-btn">
            <div class="icon-box">
                <i class="fa-solid fa-terminal"></i>
            </div>

            <p>Ethical Hacking</p>
        </a>

        <a href="{% url 'Marketing' %}" class="topic-btn">
            <div class="icon-box">
                <i class="fa-solid fa-bullhorn"></i>
            </div>

            <p>Marketing</p>
        </a>

        <a href="{% url 'Another' %}" class="topic-btn">
            <div class="icon-box">
                <i class="fa-solid fa-blog"></i>
            </div>

            <p>Another choice</p>
        </a>

    </div>

    <div class="contact">

        <h2 class="h2">Let's Talk</h2>

        <div class="wrapper">

            <p>
                Do you want to learn more about how I can help your company overcome problems? Let us
                have a
                conversation.
            </p>

            <ul class="social-link">

                <li>
                    <a href="#" class="icon-box discord">
                        <ion-icon name="logo-discord"></ion-icon>
                    </a>
                </li>

                <li>
                    <a href="#" class="icon-box twitter">
                        <ion-icon name="logo-twitter"></ion-icon>
                    </a>
                </li>

                <li>
                    <a href="#" class="icon-box facebook">
                        <ion-icon name="logo-facebook"></ion-icon>
                    </a>
                </li>

            </ul>

        </div>

    </div>

</div>

Blog_Project/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<body class="dark-theme">

    {% include 'blog/header.html' %}

    <main>

        <div class="main">

            <div class="container">


                <div class="blog">

                    <div class="blog-card-group">

                        <!-- Add comment -->
                        <div class="blog-card3" style=" padding:80px 25px;">
                            <h2 class="h2">Contact Us</h2>
                            {% if messages %}
                            {% for message in messages %}

                            <h2 style="color: green;">{{message}}</h2>

                            {% endfor %}
                            {% endif %}


                            <div class="blog-content-wrapper">

                                <form method="POST" id="contact-form">
                                    {% csrf_token %}
                                    <label for="id_body" class="h4">Name:</label>
                                    <input type="text" name="user_name" cols="40" rows="10" required id="text">
                                    <label for="id_body" class="h4">Email:</label>
                                    <input type="email" name="user_email" cols="40" rows="10" required id="email">
                                    <label for="id_body" class="h4">massege:</label>
                                    <textarea name="message" cols="40" rows="10" required id="message"
                                        style="margin-bottom: 25px;"></textarea>

                                    <button type="submit" class="button-contact">
                                        send message
                                    </button>
                                    <p id="contact-message"></p>
                                </form>

                            </div>

                        </div>

                    </div>

                </div>

            </div>


        </div>

    </main>

    {% include 'blog/footer.html' %}

    <!-- javascripts  -->
    <script src="{% static 'js/scriptblogger.js'%}"></script>
    <script src="{% static 'js/scriptlabel.js'%}"></script>
    <script>
        // EMAIL JS
        // complete you information 'service id' , 'template id' and 'Public Key' from https://www.emailjs.com/

        const contactForm = document.getElementById('contact-form'),
            contactMessage = document.getElementById('contact-message')



        const sendEmail = (e) => {
            e.preventDefault()

            emailjs.sendForm('service id', 'template id', '#contact-form', 'Public Key')
                .then(() => {

                    contactMessage.textContent = 'Message sent successfully '

                    setTimeout(() => {
                        contactMessage.textContent = ''
                    }, 5000)

                    contactForm.reset()

                }, () => {

                    contactMessage.textContent = 'Message not sent (service error)'
                })
        }

        contactForm.addEventListener('submit', sendEmail)

    </script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>
    <!--- ionicon link -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>
{% endblock content %}

Blog_Project/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<body class="dark-theme">

    {% include 'blog/header.html' %}

    <main>

        <div class="main">

            <div class="container">


                <div class="blog">

                    <h2 class="h2">{{post.title}}</h2>
                    <div class="blog-card-group">

                        <div class="blog-card2">

                            <div class="blog-card-banner">
                                <img src="{{post.image.url}}"
                                    alt="Building microservices with Dropwizard, MongoDB & Docker" width="250"
                                    class="blog-banner-img">
                            </div>

                            <div class="blog-content-wrapper">

                                <span class="blog-topic text-tiny">{{post.categry}}</span>

                                <h3>
                                    <span class="h3">
                                        {{post.title1}}
                                    </span>
                                </h3>

                                <p class="blog-text">
                                    {{post.content}}
                                </p>
                                {% if post.image2 %}
                                <div class="blog-card-banner" style="margin-top:19px;margin-bottom:17px;">
                                    <img src="{{post.image2.url}}"
                                        alt="Building microservices with Dropwizard, MongoDB & Docker" width="250"
                                        class="blog-banner-img">
                                </div>
                                {% endif %}

                                <h3>
                                    <span class="h3">
                                        {{post.title2}}
                                    </span>
                                </h3>

                                <p class="blog-text">
                                    {{post.content2}}
                                </p>

                                <div class="wrapper-flex">

                                    <div class="profile-wrapper">
                                        <img src="{{post.author.profile.image.url}}" alt="Julia Walker" width="50">
                                    </div>

                                    <div class="wrapper">
                                        <span class="h4">{{post.author}}</span>

                                        <p class="text-sm">
                                            <time datetime="2022-01-17">{{post.post_date|date:'d-m-Y'}}</time>
                                            <time>{{post.post_date|time:'H:i'}}</time>
                                        </p>
                                    </div>

                                </div>

                                {% if post.author == user %}

                                <div class="wrapper-flex">

                                    <div class="wrapper2">
                                        <button class="btn3 edit-blog"><a
                                                href="{% url 'post_update' post.pk %}">Edit</a></button>
                                        <button class="btn3 delete"><a
                                                href="{% url 'post_delete' post.pk %}">Delete</a></button>
                                    </div>

                                </div>

                                {% endif %}

                            </div>

                        </div>
                        <!-- comments -->
                        <div class="blog-card3">
                            <h2 class="h2">Comments ({{comments.count}})</h2>
                            {% for comment in comments %}

                            <div class="blog-content-wrapper-comment">

                                <h3>
                                    <span class="h3">
                                        {{comment.name}}
                                        <span style="font-size: var(--fs-4);color: var(--foreground-tertiary);"
                                            datetime="2022-01-17">{{comment.coment_date|date:'d-m-Y'}}</span>
                                        <span
                                            style="font-size: var(--fs-4);color: var(--foreground-tertiary);">{{comment.coment_date|time:'H:i'}}</span>
                                    </span>
                                </h3>



                                <p class="blog-text">
                                    {{comment.body}}
                                </p>

                            </div>

                            {% empty %}

                            <div class="blog-content-wrapper">

                                <h2 class="h4">
                                    No comments
                                </h2>

                            </div>

                            {% endfor %}

                        </div>
                        <!-- Add comment -->
                        {% include 'blog/add_comment.html' %}

                    </div>

                </div>


                {% include 'blog/component.html' %}

            </div>

        </div>

    </main>

    {% include 'blog/footer.html' %}

    <!-- javascripts  -->
    <script src="{% static 'js/scriptblogger.js'%}"></script>
    <script src="{% static 'js/scriptlabel.js'%}"></script>
    <!--- ionicon link -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>
{% endblock content %}

Blog_Project/blog/templates/blog/footer.html
 {% load static %}
 <footer>

    <div class="container">

      <div class="wrapper">

        <a href="#" class="footer-logo">
          <img src="{% static 'images/logo-light.svg'%}" alt="DevBlog's Logo" width="150" class="logo-light">
          <img src="{% static 'images/logo-dark.svg'%}" alt="DevBlog's Logo" width="150" class="logo-dark">
        </a>

        <p class="footer-text">
          Learn about Web accessibility, Web performance, and Database management.
        </p>

      </div>

      <div class="wrapper">

        <p class="footer-title">Quick Links</p>

        <ul>

          <li>
            <a href="{% url 'home' %}" class="footer-link">Home</a>
          </li>

          <li>
            <a href="{% url 'contact' %}" class="footer-link">Contact Us</a>
          </li>

        </ul>

      </div>


    </div>

    <p class="copyright">
      &copy; Copyright 2022 <a href="#">DevBlog</a>
    </p>

  </footer>

Blog_Project/blog/templates/blog/header.html
{% load static %}
<header>

  <div class="container">

    <nav class="navbar">
      
      <a href="{% url 'home' %}">
        <img src="{% static 'images/logo-light.svg'%}" alt="Devblog's logo" class="logo-light">
        <img src="{% static 'images/logo-dark.svg'%}" alt="Devblog's logo" class="logo-dark">
      </a>

      <div class="btn-group">
        <button class="theme-btn theme-btn-mobile dark">
          <ion-icon name="moon" class="moon"></ion-icon>
          <ion-icon name="sunny" class="sun"></ion-icon>
        </button>

        <button class="nav-menu-btn">
          <ion-icon name="menu-outline"></ion-icon>
        </button>

      </div>

      <div class="flex-wrapper">

        {% if user.is_authenticated %}
        <ul class="desktop-nav">

          <li>
            <a href="{% url 'home' %}" class="nav-link">Home</a>
          </li>

          <li>
            <a href="{% url 'profile' %}" class="nav-link">Profile</a>
          </li>
          
          <li>
            <a href="{% url 'new_post' %}" class="nav-link">New Post</a>
          </li>

          <li>
            <a href="{% url 'logout' %}" class="nav-link">Logout</a>
          </li>

        </ul>
        {% else %}
        <ul class="desktop-nav">

          <li>
            <a href="{% url 'home' %}" class="nav-link">Home</a>
          </li>

          <li>
            <a href="{% url 'login' %}" class="nav-link">Login</a>
          </li>

          <li>
            <a href="{% url 'register' %}" class="nav-link">Register</a>
          </li>

        </ul>

        {% endif %}


        <button class="theme-btn theme-btn-desktop dark">
          <ion-icon name="moon" class="moon"></ion-icon>
          <ion-icon name="sunny" class="sun"></ion-icon>
        </button>

      </div>


      <div class="mobile-nav">

        <button class="nav-close-btn">
          <ion-icon name="close-outline"></ion-icon>
        </button>

        <div class="wrapper">

          <p class="h3 nav-title">Main Menu</p>
          {% if user.is_authenticated %}
          <ul>
            <li class="nav-item">
              <a href="{% url 'home' %}" class="nav-link">Home</a>
            </li>

            <li class="nav-item">
              <a href="{% url 'profile' %}" class="nav-link">Profile</a>
            </li>

            <li class="nav-item">
              <a href="{% url 'new_post' %}" class="nav-link">New Post</a>
            </li>

          </ul>
          {% else %}
          <ul>

            <li>
              <a href="{% url 'home' %}" class="nav-link">Home</a>
            </li>

            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">Login</a>
            </li>

            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link">Register</a>
            </li>
          </ul>
          {% endif %}
        </div>

        <div class="topics">

          <p class="h3 nav-title">Topics</p>

          <ul>
            <li class="nav-item">
              <a href="{% url 'programming' %}" class="nav-link">Developpment</a>
            </li>

            <li class="nav-item">
              <a href="{% url 'EH' %}" class="nav-link">Ethical Hacking</a>
            </li>

            <li class="nav-item">
              <a href="{% url 'Marketing'%}" class="nav-link">Marketing</a>
            </li>
          </ul>

        </div>
        {% if user.is_authenticated %}

        <div>

          <button class="btn2"><a href="{% url 'logout' %}">Logout</a></button>

        </div>


        {% endif %}

      </div>

    </nav>

  </div>

</header>

Blog_Project/blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<body class="dark-theme">

    {% include 'blog/header.html' %}

    <main>

        <div class="main">

            <div class="container">


                <div class="blog">

                    <div class="blog-card-group">

                        <!-- Add comment -->
                        <div class="blog-card3" style="padding:80px 25px;">
                            <h2 class="h2">Add New Post</h2>

                            <div class="blog-content-wrapper">

                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{form}}
                                    <input type="submit" value="Post" style="margin-top:15px;">
                                </form>

                            </div>

                        </div>

                    </div>

                </div>


                {% include 'blog/component.html' %}

            </div>

        </div>

    </main>

    {% include 'blog/footer.html' %}

    <!-- javascripts  -->
    <script src="{% static 'js/scriptblogger.js'%}"></script>
    <script src="{% static 'js/scriptlabel.js'%}"></script>
    <!--- ionicon link -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>

</html>
{% endblock content %}

Blog_Project/blog/templates/blog/pagination.html
                    
                    <div class="container-paginate">
                        {% if page.has_previous %}
                        <button class="button-paginate prevNext active1" id="prev" >
                            <a href="?page={{page.previous_page_number}}">Prev</a>
                            
                        </button>
                        {% else %}
                        <button disabled class="button-paginate prevNext disabled" id="prev" >
                            <a href="#">Prev</a>
                            
                        </button>
                        {% endif %}
                        
                        <div class="links-paginate">
                            page {{page.number}} of {{page.paginator.num_pages}}
                        </div>

                        {% if page.has_next %}
                        <button class="button-paginate prevNext active1" id="next">
                            <a href="?page={{page.next_page_number}}">Next</a>
                        </button>
                        {% else %}
                        <button disabled class="button-paginate disabled prevNext" id="next">
                            <a href="#">Next</a>
                        </button>
                        {% endif %}
                    </div> 
                    